# Generated by Django 2.1.7 on 2019-03-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_butterfly_flowers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('butterfly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Butterfly')),
            ],
        ),
    ]
